# Generated by Django 5.0.6 on 2024-10-28 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "events",
                    models.ManyToManyField(blank=True, to="events.historicalevent"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WhatIfScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "modified_events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scenarios",
                        to="events.historicalevent",
                    ),
                ),
                (
                    "original_timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timeline.timeline",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_create_scenario", "Can create scenario"),
                    ("can_edit_scenario", "Can edit scenario"),
                    ("can_delete_scenario", "Can delete scenario"),
                ],
            },
        ),
    ]
