# Generated by Django 5.0.6 on 2024-10-28 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("confidence_score", models.FloatField()),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("CYCLICAL", "Cyclical Pattern"),
                            ("CAUSAL", "Cause-Effect Pattern"),
                            ("BEHAVIORAL", "Human Behavior Pattern"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("prediction", models.TextField()),
                ("probability", models.FloatField()),
                ("relevant_factors", models.JSONField()),
                ("prediction_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="QualityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("accuracy_score", models.FloatField()),
                ("completeness_score", models.FloatField()),
                ("source_reliability", models.FloatField()),
                ("peer_review_status", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="FactCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim", models.TextField()),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("DISPUTED", "Disputed"),
                            ("DEBUNKED", "Debunked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence", models.TextField()),
                ("confidence_score", models.FloatField()),
                (
                    "verified_by",
                    models.ManyToManyField(
                        limit_choices_to={"is_staff": True}, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
