# Generated by Django 5.0.6 on 2024-10-28 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpattern",
            name="supporting_events",
            field=models.ManyToManyField(to="events.historicalevent"),
        ),
        migrations.AddField(
            model_name="predictivemodel",
            name="based_on_patterns",
            field=models.ManyToManyField(to="core.historicalpattern"),
        ),
        migrations.AddField(
            model_name="qualitymetrics",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
